// charactersData.js

export const characters = [
  {
    id: 1,
    name: "Naruto Uzumaki",
    village: "Hidden Leaf",
    rank: "Hokage",
    clan: "Uzumaki",
    jutsu: [
      "Rasengan",
      "Shadow Clone Jutsu",
      "Sage Mode",
      "Rasenshuriken",
      "Tailed Beast Bomb",
    ],
    affiliation: ["Team 7", "Team Konohamaru", "Allied Shinobi Forces"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: [
      "Wind Release",
      "Fire Release",
      "Water Release",
      "Earth Release",
      "Lightning Release",
    ],
    family: [
      "Minato Namikaze (Father)",
      "Kushina Uzumaki (Mother)",
      "Hinata Hyuga (Wife)",
      "Boruto Uzumaki (Son)",
      "Himawari Uzumaki (Daughter)",
    ],
    personality:
      "Energetic, determined, loyal, and brave. Known for his infectious optimism and never-give-up attitude.",
    missions_completed: { D: 7, C: 1, B: 2, A: 4, S: 3 },
    mentor: "Kakashi Hatake, Jiraiya, Iruka Umino",
    students: ["Konohamaru Sarutobi"],
    allies: [
      "Sasuke Uchiha",
      "Sakura Haruno",
      "Shikamaru Nara",
      "Gaara",
      "Kurama (Nine-Tails)",
    ],
    enemies: ["Orochimaru", "Akatsuki", "Kaguya Ōtsutsuki"],
    weapons: ["Kunai", "Shuriken"],
    summonings: ["Toad", "Kurama (Nine-Tails)"],
    background:
      "Orphaned at birth, Naruto grew up facing prejudice but always aspired to become the Hokage. He holds the Nine-Tails fox, Kurama, inside him.",
    achievements: [
      "Defeated Pain",
      "Ended the Fourth Great Ninja War",
      "Became the Seventh Hokage",
      "United all the Tailed Beasts",
    ],
    hobbies: "Eating ramen, training, pulling pranks",
    quotes: [
      "I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way!",
      "I'm going to become the next Hokage!",
    ],
    appearance:
      "Blond hair, blue eyes, whisker marks on cheeks. Typically seen wearing an orange jumpsuit.",
    transformations: ["Sage Mode", "Kurama Chakra Mode", "Six Paths Sage Mode"],
    goals: [
      "Become Hokage",
      "Protect the village",
      "Bring Sasuke back to the village",
    ],
    voice_actor: { japanese: "Junko Takeuchi", english: "Maile Flanagan" },
    first_appearance: "Manga Chapter 1",
    theme_song: "Wind",
  },
  {
    id: 2,
    name: "Sasuke Uchiha",
    village: "Hidden Leaf",
    rank: "Rogue Ninja",
    clan: "Uchiha",
    jutsu: [
      "Chidori",
      "Fire Release: Great Fireball Technique",
      "Amaterasu",
      "Susanoo",
      "Indra's Arrow",
    ],
    affiliation: ["Team 7", "Taka", "Akatsuki (temporary)"],
    kekkeiGenkai: ["Sharingan", "Mangekyō Sharingan", "Rinnegan"],
    status: "Alive",
    natureType: [
      "Fire Release",
      "Lightning Release",
      "Wind Release",
      "Earth Release",
      "Water Release",
    ],
    family: [
      "Fugaku Uchiha (Father)",
      "Mikoto Uchiha (Mother)",
      "Itachi Uchiha (Brother)",
      "Sakura Haruno (Wife)",
      "Sarada Uchiha (Daughter)",
    ],
    personality:
      "Calm, focused, and determined. Initially cold and indifferent, his bond with his teammates grows over time.",
    missions_completed: { D: 7, C: 1, B: 2, A: 6, S: 3 },
    mentor: "Kakashi Hatake, Orochimaru",
    students: null,
    allies: ["Naruto Uzumaki", "Karin", "Suigetsu Hōzuki", "Jūgo"],
    enemies: ["Itachi Uchiha (formerly)", "Danzo Shimura", "Kaguya Ōtsutsuki"],
    weapons: ["Kusanagi Sword", "Shuriken", "Kunai"],
    summonings: ["Hawk", "Snake"],
    background:
      "After witnessing the massacre of his clan at the hands of his brother Itachi, Sasuke vows to avenge them by any means necessary.",
    achievements: [
      "Defeated Danzo Shimura",
      "Assisted in defeating Kaguya Ōtsutsuki",
      "Became a highly skilled shinobi recognized worldwide",
    ],
    hobbies: "Training, traveling",
    quotes: [
      "I have long since closed my eyes... My only goal is in the darkness.",
      "I'm going to restore my clan and destroy a certain someone.",
    ],
    appearance:
      "Black hair, onyx eyes, often seen wearing a blue shirt with the Uchiha crest on its back.",
    transformations: [
      "Curse Mark Stage 1 and 2",
      "Eternal Mangekyō Sharingan",
      "Rinnegan",
    ],
    goals: [
      "Avenge his clan by killing Itachi (formerly)",
      "Protect Konoha and the shinobi world",
    ],
    voice_actor: { japanese: "Noriaki Sugiyama", english: "Yuri Lowenthal" },
    first_appearance: "Manga Chapter 3",
    theme_song: "Hyouhaku + Kokuten",
  },
  {
    id: 3,
    name: "Sakura Haruno",
    village: "Hidden Leaf",
    rank: "Jonin",
    clan: "Haruno",
    jutsu: [
      "Cherry Blossom Impact",
      "Medical Ninjutsu",
      "Strength of a Hundred Seal",
      "Mystical Palm Technique",
      "Katsuyu: Immense Network Healing",
    ],
    affiliation: ["Team 7", "Team Kakashi", "Konoha Medical Team"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: ["Yin Release"],
    family: [
      "Kizashi Haruno (Father)",
      "Mebuki Haruno (Mother)",
      "Sasuke Uchiha (Husband)",
      "Sarada Uchiha (Daughter)",
    ],
    personality:
      "Determined, caring, and strong-willed. Initially infatuated with Sasuke, she grows to become a skilled medical ninja.",
    missions_completed: { D: 12, C: 9, B: 6, A: 7, S: 3 },
    mentor: "Kakashi Hatake, Tsunade Senju",
    students: null,
    allies: ["Naruto Uzumaki", "Ino Yamanaka", "Hinata Hyuga", "Shizune"],
    enemies: ["Kaguya Ōtsutsuki", "Shin Uchiha"],
    weapons: ["Kunai", "Shuriken", "Antidote"],
    summonings: ["Katsuyu"],
    background:
      "Initially known for her infatuation with Sasuke, Sakura undergoes rigorous training under Tsunade to become a top medical ninja.",
    achievements: [
      "Became a top medical ninja",
      "Played a key role in the Fourth Great Ninja War",
      "Helped in defeating Kaguya Ōtsutsuki",
    ],
    hobbies: "Playing trivia games, collecting herbal medicines",
    quotes: [
      "I've always considered myself to be a true ninja... but those were just empty words, because Sasuke and Naruto were always in the lead! But now it's my turn to take the lead, and all of you can watch me from the background!",
    ],
    appearance:
      "Pink hair, green eyes, often seen wearing a red dress with a white circle on the back.",
    transformations: ["Strength of a Hundred Seal Activation"],
    goals: [
      "Protect Konoha and its people",
      "Support Naruto and Sasuke in their endeavors",
    ],
    voice_actor: { japanese: "Chie Nakamura", english: "Kate Higgins" },
    first_appearance: "Manga Chapter 3",
    theme_song: "Glad You're My Friend",
  },
  {
    id: 4,
    name: "Kakashi Hatake",
    village: "Hidden Leaf",
    rank: "Hokage",
    clan: "Hatake",
    jutsu: [
      "Raikiri",
      "Kamui",
      "Shadow Clone Jutsu",
      "Multiple Shadow Clone Jutsu",
      "Water Dragon Bullet Technique",
    ],
    affiliation: ["Team 7", "Team Kakashi", "Third Great Ninja War"],
    kekkeiGenkai: "Sharingan",
    status: "Alive",
    natureType: [
      "Lightning Release",
      "Water Release",
      "Earth Release",
      "Fire Release",
    ],
    family: ["Sakumo Hatake (Father)"],
    personality:
      "Calm, collected, and analytical. Known for his tardiness and reading the 'Icha Icha' series.",
    missions_completed: { D: 197, C: 190, B: 414, A: 298, S: 42 },
    mentor: "Minato Namikaze",
    students: ["Naruto Uzumaki", "Sasuke Uchiha", "Sakura Haruno"],
    allies: ["Might Guy", "Asuma Sarutobi", "Kurenai Yūhi"],
    enemies: ["Kaguya Ōtsutsuki", "Madara Uchiha", "Obito Uchiha (formerly)"],
    weapons: ["Kunai", "Shuriken", "White Light Chakra Sabre"],
    summonings: ["Ninken (Ninja Dogs)"],
    background:
      "Once known as the 'Copy Ninja' for his Sharingan, Kakashi is a prodigious talent, having been promoted to Jonin during his teenage years. He lost his left eye during a mission, which was replaced with a Sharingan by his teammate, Obito Uchiha.",
    achievements: [
      "Became the Sixth Hokage",
      "Played a key role in the Fourth Great Ninja War",
      "Trained the Seventh Hokage, Naruto Uzumaki",
    ],
    hobbies:
      "Reading (particularly the 'Icha Icha' series), visiting the Memorial Stone",
    quotes: [
      "I'm Kakashi Hatake. Things I like and things I hate... I don't feel like telling you that. My dreams for the future... never really thought about it. As for my hobbies... I have lots of hobbies.",
    ],
    appearance:
      "Silver hair, masked face, often seen wearing a standard Jonin uniform with a flak jacket.",
    transformations: ["Mangekyō Sharingan", "Perfect Susanoo (temporary)"],
    goals: [
      "Protect Konoha and its shinobi",
      "Pass on his teachings to the next generation",
    ],
    voice_actor: { japanese: "Kazuhiko Inoue", english: "Dave Wittenberg" },
    first_appearance: "Manga Chapter 3",
    theme_song: "Cold",
  },
  {
    id: 5,
    name: "Hinata Hyuga",
    village: "Hidden Leaf",
    rank: "Chunin",
    clan: "Hyuga",
    jutsu: [
      "Gentle Fist",
      "Protective Eight Trigrams Sixty-Four Palms",
      "Twin Lion Fists",
      "Gentle Step Twin Lion Fists",
    ],
    affiliation: ["Team Kurenai", "Second Division", "Allied Shinobi Forces"],
    kekkeiGenkai: "Byakugan",
    status: "Alive",
    natureType: ["Yin Release"],
    family: [
      "Hiashi Hyuga (Father)",
      "Hanabi Hyuga (Sister)",
      "Neji Hyuga (Cousin)",
      "Naruto Uzumaki (Husband)",
      "Boruto Uzumaki (Son)",
      "Himawari Uzumaki (Daughter)",
    ],
    personality:
      "Shy, kind-hearted, and very polite. She has a strong sense of right and wrong and can be very courageous when motivated.",
    missions_completed: { D: 33, C: 9, B: 23, A: 8, S: 2 },
    mentor: "Kurenai Yūhi",
    students: null,
    allies: ["Kiba Inuzuka", "Shino Aburame", "Sakura Haruno"],
    enemies: ["Pain", "Toneri Ōtsutsuki"],
    weapons: ["Kunai", "Shuriken"],
    summonings: null,
    background:
      "As the former heiress of the main house of the Hyuga Clan, Hinata struggled with expectations but found her own path after being inspired by Naruto.",
    achievements: [
      "Mastered the Gentle Fist technique",
      "Played a crucial role in the Fourth Great Ninja War",
      "Helped Naruto understand love",
    ],
    hobbies: "Pressing flowers, cooking",
    quotes: [
      "I used to always cry and give up... I made many wrong turns... But you... You helped me find the right path... I always chased after you... I wanted to catch up to you... I wanted to walk beside you all the time... I just wanted to be with you... You changed me! Your smile is what saved me! That's why I'm not afraid to die protecting you! Because... I love you...",
    ],
    appearance:
      "Long dark blue hair, pale lavender eyes characteristic of the Byakugan, often seen wearing a loose-fitting, lavender and cream hooded-jacket.",
    transformations: null,
    goals: [
      "Support and protect Naruto",
      "Become a strong kunoichi in her own right",
    ],
    voice_actor: { japanese: "Nana Mizuki", english: "Stephanie Sheh" },
    first_appearance: "Manga Chapter 34",
    theme_song: "Gentle Song",
  },
  {
    id: 6,
    name: "Shikamaru Nara",
    village: "Hidden Leaf",
    rank: "Jonin",
    clan: "Nara",
    jutsu: [
      "Shadow Possession Jutsu",
      "Shadow Strangle Jutsu",
      "Shadow Stitching Jutsu",
    ],
    affiliation: ["Team 10", "Allied Shinobi Forces"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: ["Yin Release"],
    family: [
      "Shikaku Nara (Father)",
      "Yoshino Nara (Mother)",
      "Temari (Wife)",
      "Shikadai Nara (Son)",
    ],
    personality:
      "Laid-back, intelligent, strategic thinker. Often says, 'What a drag.'",
    missions_completed: { D: 8, C: 3, B: 6, A: 3, S: 2 },
    mentor: "Asuma Sarutobi",
    students: null,
    allies: ["Choji Akimichi", "Ino Yamanaka", "Naruto Uzumaki"],
    enemies: ["Hidan", "Kakuzu"],
    weapons: ["Kunai", "Shuriken"],
    summonings: null,
    background:
      "Known for his intelligence and strategic mind, Shikamaru is a key figure in many of Konoha's battles.",
    achievements: [
      "Became a Chunin at a young age",
      "Played a key role in the Fourth Great Ninja War as a strategist",
    ],
    hobbies: "Watching clouds, playing shogi",
    quotes: [
      "I could tell you, but you're still too weak. I'd rather not take you on as an opponent. I'd hate to get any dumber by association.",
    ],
    appearance:
      "Ponytail, wears earrings given by his sensei, Asuma. Typically seen in a green flak jacket.",
    transformations: null,
    goals: ["Protect Konoha", "Live a peaceful and uneventful life"],
    voice_actor: { japanese: "Showtaro Morikubo", english: "Tom Gibis" },
    first_appearance: "Manga Chapter 34",
    theme_song: "Thinking of Asuma",
  },
  {
    id: 7,
    name: "Rock Lee",
    village: "Hidden Leaf",
    rank: "Jonin",
    clan: null,
    jutsu: [
      "Leaf Whirlwind",
      "Leaf Hurricane",
      "Primary Lotus",
      "Hidden Lotus",
      "Eight Gates",
    ],
    affiliation: ["Team Guy", "Allied Shinobi Forces"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: null,
    family: ["Metal Lee (Son)"],
    personality:
      "Energetic, determined, and passionate. Believes in the power of youth and hard work.",
    missions_completed: { D: 20, C: 8, B: 7, A: 4, S: 1 },
    mentor: "Might Guy",
    students: null,
    allies: ["Neji Hyuga", "Tenten", "Naruto Uzumaki"],
    enemies: ["Gaara (formerly)"],
    weapons: ["Nunchaku", "Kunai"],
    summonings: null,
    background:
      "Despite his inability to use ninjutsu or genjutsu, Lee is determined to become a great ninja through hard work and taijutsu.",
    achievements: [
      "Mastered the Eight Gates",
      "Defended Konoha during Pain's invasion",
    ],
    hobbies: "Training, challenging Neji and Sasuke to fights",
    quotes: [
      "I want to prove that even if I can't use ninjutsu or genjutsu, I can still become a great ninja.",
    ],
    appearance:
      "Bowl-cut hair, thick eyebrows, wears a white, long-sleeved kimono shirt with a martial arts belt and dark pants, giving him a more traditional Chinese appearance.",
    transformations: ["Eight Gates"],
    goals: [
      "Become a respected ninja through taijutsu alone",
      "Prove that hard work can beat natural talent",
    ],
    voice_actor: { japanese: "Yoichi Masukawa", english: "Brian Donovan" },
    first_appearance: "Manga Chapter 36",
    theme_song: "Run",
  },
  {
    id: 8,
    name: "Gaara",
    village: "Hidden Sand",
    rank: "Kazekage",
    clan: null,
    jutsu: [
      "Sand Coffin",
      "Sand Tsunami",
      "Desert Layered Imperial Funeral Seal",
    ],
    affiliation: ["Sunagakure", "Allied Shinobi Forces"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: ["Wind Release", "Earth Release"],
    family: ["Rasa (Father)", "Temari (Sister)", "Kankuro (Brother)"],
    personality:
      "Initially cold and detached, he later becomes more compassionate and protective.",
    missions_completed: { D: 0, C: 9, B: 8, A: 6, S: 3 },
    mentor: "Baki",
    students: null,
    allies: ["Naruto Uzumaki", "Rock Lee", "Shikamaru Nara"],
    enemies: ["Deidara", "Sasori"],
    weapons: ["Gourd of Sand"],
    summonings: null,
    background:
      "Once a Jinchuriki of the One-Tail, Gaara was feared in his village. His life changes after meeting Naruto.",
    achievements: [
      "Became the Fifth Kazekage",
      "Played a key role in the Fourth Great Ninja War",
    ],
    hobbies: "Meditation, sand manipulation",
    quotes: [
      "I used to think 'I want to die.' Now, I have something I want to protect. That's why I'm willing to die.",
    ],
    appearance:
      "Red hair, tattoo on the forehead that reads 'love', carries a giant sand gourd on his back.",
    transformations: ["One-Tail Form"],
    goals: ["Protect Sunagakure", "Understand and experience true friendship"],
    voice_actor: { japanese: "Akira Ishida", english: "Liam O'Brien" },
    first_appearance: "Manga Chapter 35",
    theme_song: "Sabaku",
  },
  {
    id: 9,
    name: "Tenten",
    village: "Hidden Leaf",
    rank: "Jonin",
    clan: null,
    jutsu: [
      "Twin Rising Dragons",
      "Manipulated Tools: Heavenly Chain Disaster",
      "Manipulated Tools: Super Heavenly Chain Disaster",
    ],
    affiliation: ["Team Guy", "Allied Shinobi Forces"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: null,
    family: null,
    personality:
      "Pragmatic, passionate about weaponry, and dreams of becoming a legendary kunoichi.",
    missions_completed: { D: 28, C: 23, B: 3, A: 8, S: 2 },
    mentor: "Might Guy",
    students: null,
    allies: ["Neji Hyuga", "Rock Lee", "Hinata Hyuga"],
    enemies: ["Kisame Hoshigaki"],
    weapons: [
      "Kunai",
      "Shuriken",
      "Giant Folding Fan",
      "Various Summoned Weapons",
    ],
    summonings: null,
    background:
      "Tenten specializes in weaponry and dreams of becoming as legendary as Tsunade.",
    achievements: [
      "Became a weapons specialist",
      "Assisted in the Fourth Great Ninja War",
    ],
    hobbies: "Weapon collecting",
    quotes: ["I'm the top kunoichi of the Hidden Leaf!"],
    appearance:
      "Brown hair tied in two buns, wears a pink qipao dress with white pants.",
    transformations: null,
    goals: [
      "Master all types of ninja tools",
      "Support her teammates in battle",
    ],
    voice_actor: { japanese: "Yukari Tamura", english: "Danielle Judovits" },
    first_appearance: "Manga Chapter 36",
    theme_song: "Tool Princess",
  },

  {
    id: 10,
    name: "Kankuro",
    village: "Hidden Sand",
    rank: "Jonin",
    clan: null,
    jutsu: [
      "Black Secret Technique Machine One Shot",
      "Puppet Technique",
      "Black Secret Technique Salamander",
    ],
    affiliation: ["Sunagakure", "Allied Shinobi Forces"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: null,
    family: ["Rasa (Father)", "Temari (Sister)", "Gaara (Brother)"],
    personality:
      "Protective of his siblings, especially Gaara. Skilled puppeteer.",
    missions_completed: { D: 3, C: 12, B: 4, A: 7, S: 1 },
    mentor: "Baki",
    students: null,
    allies: ["Naruto Uzumaki", "Shikamaru Nara"],
    enemies: ["Sasori", "Deidara"],
    weapons: ["Crow Puppet", "Black Ant Puppet", "Salamander Puppet"],
    summonings: null,
    background:
      "Kankuro is a master puppeteer and uses his skills to control deadly puppets in battle.",
    achievements: [
      "Became a puppet master",
      "Played a key role in the Fourth Great Ninja War",
    ],
    hobbies: "Puppet maintenance",
    quotes: ["I'll show you the true art of puppetry!"],
    appearance:
      "Dark circles around his eyes, wears a black hood and carries his puppets on his back.",
    transformations: null,
    goals: ["Protect Sunagakure", "Support his brother, Gaara"],
    voice_actor: { japanese: "Yasuyuki Kase", english: "Michael Lindsay" },
    first_appearance: "Manga Chapter 35",
    theme_song: "Puppet Master",
  },
  {
    id: 11,
    name: "Ino Yamanaka",
    village: "Hidden Leaf",
    rank: "Jonin",
    clan: "Yamanaka",
    jutsu: [
      "Mind Body Switch Technique",
      "Mind Body Disturbance Technique",
      "Mind Clone Switch Technique",
    ],
    affiliation: ["Team 10", "Allied Shinobi Forces"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: ["Yin Release"],
    family: [
      "Inoichi Yamanaka (Father)",
      "Sai (Husband)",
      "Inojin Yamanaka (Son)",
    ],
    personality: "Confident, caring, and has a rivalry with Sakura Haruno.",
    missions_completed: { D: 22, C: 9, B: 6, A: 3, S: 2 },
    mentor: "Asuma Sarutobi",
    students: null,
    allies: ["Shikamaru Nara", "Choji Akimichi", "Sakura Haruno"],
    enemies: ["Hidan", "Kakuzu"],
    weapons: ["Kunai", "Shuriken"],
    summonings: null,
    background:
      "Ino is a member of the Yamanaka clan and specializes in mind-related techniques.",
    achievements: [
      "Became a key member of the Sensory Division",
      "Assisted in the Fourth Great Ninja War",
    ],
    hobbies: "Shopping, visiting flower shops",
    quotes: ["I won't lose to Sakura!"],
    appearance: "Long blonde hair, purple outfit with a red belt.",
    transformations: null,
    goals: ["Become a top-tier kunoichi", "Support her teammates in battle"],
    voice_actor: {
      japanese: "Ryoka Yuzuki",
      english: "Colleen O'Shaughnessey",
    },
    first_appearance: "Manga Chapter 34",
    theme_song: "Flower Maiden",
  },
  {
    id: 12,
    name: "Choji Akimichi",
    village: "Hidden Leaf",
    rank: "Jonin",
    clan: "Akimichi",
    jutsu: ["Human Boulder", "Partial Multi-Size Technique", "Calorie Control"],
    affiliation: ["Team 10", "Allied Shinobi Forces"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: null,
    family: [
      "Chomaru Akimichi (Father)",
      "Karui (Wife)",
      "Chocho Akimichi (Daughter)",
    ],
    personality:
      "Kind-hearted, always thinking about food, loyal to his friends.",
    missions_completed: { D: 20, C: 15, B: 8, A: 3, S: 1 },
    mentor: "Asuma Sarutobi",
    students: null,
    allies: ["Shikamaru Nara", "Ino Yamanaka", "Naruto Uzumaki"],
    enemies: ["Jirobo", "Hidan", "Kakuzu"],
    weapons: ["Kunai", "Shuriken"],
    summonings: null,
    background:
      "Choji is a member of the Akimichi clan, known for their size manipulation techniques and love for food.",
    achievements: [
      "Mastered the Akimichi clan's secret techniques",
      "Played a pivotal role in the Fourth Great Ninja War",
    ],
    hobbies: "Eating, cooking",
    quotes: ["I'm not fat, I'm just big-boned!"],
    appearance:
      "Spiky brown hair, wears a white shirt with the kanji for 'food' on it.",
    transformations: ["Butterfly Choji Mode"],
    goals: ["Protect his friends", "Become a great chef"],
    voice_actor: { japanese: "Kentaro Ito", english: "Robbie Rist" },
    first_appearance: "Manga Chapter 34",
    theme_song: "Food Lover",
  },
  {
    id: 13,
    name: "Neji Hyuga",
    village: "Hidden Leaf",
    rank: "Jonin",
    clan: "Hyuga",
    jutsu: [
      "Eight Trigrams Sixty-Four Palms",
      "Eight Trigrams Air Palm",
      "Byakugan",
    ],
    affiliation: ["Team Guy", "Allied Shinobi Forces"],
    kekkeiGenkai: "Byakugan",
    status: "Deceased",
    natureType: ["Yin Release"],
    family: [
      "Hizashi Hyuga (Father)",
      "Hinata Hyuga (Cousin)",
      "Hanabi Hyuga (Cousin)",
    ],
    personality:
      "Initially strict and bound by fate, later becomes more kind-hearted and protective.",
    missions_completed: { D: 20, C: 14, B: 12, A: 6, S: 2 },
    mentor: "Might Guy",
    students: null,
    allies: ["Rock Lee", "Tenten", "Naruto Uzumaki"],
    enemies: ["Kidomaru"],
    weapons: ["Kunai", "Shuriken"],
    summonings: null,
    background:
      "Neji was a prodigy of the Hyuga clan, but was born into the branch family and was bound by its rules.",
    achievements: [
      "Recognized as a genius of the Hyuga clan",
      "Sacrificed his life during the Fourth Great Ninja War to protect his allies",
    ],
    hobbies: "Meditation",
    quotes: ["I'm not bound by my destiny."],
    appearance:
      "Long brown hair, white eyes characteristic of the Byakugan. Wears a white kimono shirt.",
    transformations: null,
    goals: [
      "Protect his friends and family",
      "Break free from the shackles of destiny",
    ],
    voice_actor: { japanese: "Koichi Tochika", english: "Steve Staley" },
    first_appearance: "Manga Chapter 34",
    theme_song: "Destiny",
  },
  {
    id: 14,
    name: "Temari",
    village: "Hidden Sand",
    rank: "Jonin",
    clan: null,
    jutsu: [
      "Wind Scythe Jutsu",
      "Summoning: Quick Beheading Dance",
      "Wind Release: Great Task of the Dragon",
    ],
    affiliation: ["Sunagakure", "Allied Shinobi Forces"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: ["Wind Release"],
    family: [
      "Rasa (Father)",
      "Kankuro (Brother)",
      "Gaara (Brother)",
      "Shikamaru Nara (Husband)",
      "Shikadai Nara (Son)",
    ],
    personality:
      "Sharp-tongued, protective of her brothers, strategic thinker.",
    missions_completed: { D: 9, C: 12, B: 6, A: 4, S: 2 },
    mentor: "Baki",
    students: null,
    allies: ["Naruto Uzumaki", "Shikamaru Nara"],
    enemies: ["Tayuya"],
    weapons: ["Giant Folding Fan"],
    summonings: null,
    background:
      "Temari is a skilled kunoichi specializing in wind-based jutsu and wields a giant fan as her primary weapon.",
    achievements: [
      "Became a key Sunagakure representative",
      "Assisted in the Fourth Great Ninja War",
    ],
    hobbies: "Playing board games",
    quotes: ["You're not even worth my time."],
    appearance:
      "Blonde hair tied in four pigtails, carries a giant fan on her back.",
    transformations: null,
    goals: ["Protect Sunagakure", "Support her family and allies"],
    voice_actor: { japanese: "Romi Park", english: "Tara Platt" },
    first_appearance: "Manga Chapter 35",
    theme_song: "Wind Dancer",
  },
  {
    id: 15,
    name: "Asuma Sarutobi",
    village: "Hidden Leaf",
    rank: "Jonin",
    clan: "Sarutobi",
    jutsu: [
      "Flying Swallow",
      "Fire Release: Ash Pile Burning",
      "Wind Release: Dust Cloud Technique",
    ],
    affiliation: ["Konohagakure", "Twelve Guardian Ninja"],
    kekkeiGenkai: null,
    status: "Deceased",
    natureType: ["Wind Release", "Fire Release"],
    family: [
      "Hiruzen Sarutobi (Father)",
      "Biwako Sarutobi (Mother)",
      "Konohamaru Sarutobi (Nephew)",
      "Kurenai Yuhi (Lover)",
      "Mirai Sarutobi (Daughter)",
    ],
    personality: "Calm, caring, and values the next generation.",
    missions_completed: { D: 4, C: 28, B: 7, A: 13, S: 3 },
    mentor: "Hiruzen Sarutobi",
    students: ["Shikamaru Nara", "Ino Yamanaka", "Choji Akimichi"],
    allies: ["Kurenai Yuhi", "Kakashi Hatake"],
    enemies: ["Hidan", "Kakuzu"],
    weapons: ["Chakra Blades"],
    summonings: null,
    background:
      "Asuma was a former member of the Twelve Guardian Ninja and the son of the Third Hokage, Hiruzen Sarutobi.",
    achievements: [
      "Became a leader of Team 10",
      "Fought valiantly against Akatsuki members",
    ],
    hobbies: "Smoking, playing shogi",
    quotes: ["The king... is the next generation."],
    appearance:
      "Bearded with a scar on his chin, wears a sash that has the kanji for 'Fire'.",
    transformations: null,
    goals: ["Protect Konohagakure", "Train the next generation"],
    voice_actor: { japanese: "Jurota Kosugi", english: "Doug Erholtz" },
    first_appearance: "Manga Chapter 34",
    theme_song: "Guardian Ninja",
  },
  {
    id: 16,
    name: "Jiraiya",
    village: "Hidden Leaf",
    rank: "Sannin",
    clan: null,
    jutsu: ["Rasengan", "Summoning Technique (Toads)", "Sage Mode"],
    affiliation: ["Konohagakure", "Mount Myoboku"],
    kekkeiGenkai: null,
    status: "Deceased",
    natureType: ["Fire Release", "Earth Release", "Water Release"],
    family: null,
    personality:
      "Perverted, jovial, and wise. Has a deep sense of loyalty and bravery.",
    missions_completed: { D: 58, C: 345, B: 684, A: 138, S: 33 },
    mentor: "Hiruzen Sarutobi",
    students: ["Minato Namikaze", "Naruto Uzumaki"],
    allies: ["Tsunade", "Orochimaru", "Naruto Uzumaki"],
    enemies: ["Pain", "Konan"],
    weapons: ["Kunai", "Scrolls"],
    summonings: ["Gamabunta", "Gamaken", "Gama"],
    background:
      "One of the Legendary Sannin. Jiraiya is also known as the 'Toad Sage' and is Naruto's godfather.",
    achievements: [
      "Trained the Fourth Hokage",
      "Discovered the truth about Pain",
    ],
    hobbies: "Peeping, writing (Author of the 'Icha Icha' series)",
    quotes: ["I'm not a pervert... I'm a super pervert!"],
    appearance: "Tall, white spiky hair, red marks on his face.",
    transformations: ["Sage Mode"],
    goals: ["Train the next generation", "Protect the Hidden Leaf"],
    voice_actor: { japanese: "Hochu Otsuka", english: "David Lodge" },
    first_appearance: "Manga Chapter 91",
    theme_song: "Tales of a Gutsy Ninja",
  },
  {
    id: 17,
    name: "Tsunade",
    village: "Hidden Leaf",
    rank: "Sannin",
    clan: "Senju",
    jutsu: [
      "Creation Rebirth",
      "Strength of a Hundred Seal",
      "Summoning Technique (Slug)",
    ],
    affiliation: ["Konohagakure"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: ["Earth Release", "Water Release"],
    family: ["Hashirama Senju (Grandfather)", "Tobirama Senju (Granduncle)"],
    personality:
      "Tough, gambler, has a fear of blood. Deeply cares for the village and its inhabitants.",
    missions_completed: { D: 40, C: 236, B: 467, A: 81, S: 27 },
    mentor: "Hiruzen Sarutobi",
    students: ["Sakura Haruno", "Shizune"],
    allies: ["Jiraiya", "Shizune", "Naruto Uzumaki"],
    enemies: ["Orochimaru", "Kabuto Yakushi"],
    weapons: ["Kunai"],
    summonings: ["Katsuyu"],
    background:
      "One of the Legendary Sannin. Tsunade is known for her medical ninjutsu and incredible strength.",
    achievements: [
      "Became the Fifth Hokage",
      "Healed Rock Lee's damaged spine",
    ],
    hobbies: "Gambling",
    quotes: [
      "Although I'm the Hokage now... deep down, I'll always be the same scared girl.",
    ],
    appearance:
      "Blonde hair, diamond mark on her forehead. Often wears a green robe.",
    transformations: ["Strength of a Hundred Seal"],
    goals: ["Protect the Hidden Leaf", "Advance medical ninjutsu"],
    voice_actor: { japanese: "Masako Katsuki", english: "Debi Mae West" },
    first_appearance: "Manga Chapter 139",
    theme_song: "Legendary Sannin",
  },
  {
    id: 18,
    name: "Shino Aburame",
    village: "Hidden Leaf",
    rank: "Jonin",
    clan: "Aburame",
    jutsu: [
      "Insect Jamming Technique",
      "Parasitic Destruction Insect Technique",
      "Spindle Formation",
    ],
    affiliation: ["Konohagakure", "Team 8"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: ["Earth Release"],
    family: ["Shibi Aburame (Father)"],
    personality:
      "Quiet, mysterious, and analytical. Has a deep bond with his insects.",
    missions_completed: { D: 23, C: 20, B: 4, A: 2, S: 1 },
    mentor: "Kurenai Yuhi",
    students: null,
    allies: ["Hinata Hyuga", "Kiba Inuzuka", "Naruto Uzumaki"],
    enemies: ["Zaku Abumi", "Kankuro"],
    weapons: ["Kunai"],
    summonings: null,
    background:
      "Shino is a member of the Aburame clan, known for their symbiotic relationship with insects.",
    achievements: [
      "Mastered the use of his clan's insects",
      "Played a role in tracking enemies during the Fourth Great Ninja War",
    ],
    hobbies: "Entomology, collecting new insect specimens",
    quotes: ["I understand things better by observing them."],
    appearance:
      "Always seen with sunglasses and a high collar that hides his mouth. Has dark hair.",
    transformations: null,
    goals: ["Understand the world through insects", "Protect Konohagakure"],
    voice_actor: { japanese: "Shinji Kawada", english: "Derek Stephen Prince" },
    first_appearance: "Manga Chapter 34",
    theme_song: "Insect Whisperer",
  },
  {
    id: 19,
    name: "Kiba Inuzuka",
    village: "Hidden Leaf",
    rank: "Jonin",
    clan: "Inuzuka",
    jutsu: [
      "Fang Passing Fang",
      "Beast Human Clone",
      "Man Beast Combination Transformation: Double-Headed Wolf",
    ],
    affiliation: ["Konohagakure", "Team 8"],
    kekkeiGenkai: null,
    status: "Alive",
    natureType: null,
    family: ["Tsume Inuzuka (Mother)", "Hana Inuzuka (Sister)"],
    personality:
      "Brash, competitive, and has a strong bond with his dog, Akamaru.",
    missions_completed: { D: 23, C: 14, B: 8, A: 3, S: 1 },
    mentor: "Kurenai Yuhi",
    students: null,
    allies: ["Hinata Hyuga", "Shino Aburame", "Naruto Uzumaki"],
    enemies: ["Sakon and Ukon"],
    weapons: ["Kunai"],
    summonings: ["Akamaru"],
    background:
      "Kiba is a member of the Inuzuka clan, known for their canine companions and beast-like fighting styles.",
    achievements: [
      "Mastered the clan's beast mimicry techniques",
      "Supported the main forces during the Fourth Great Ninja War",
    ],
    hobbies: "Walking with Akamaru, training",
    quotes: ["Akamaru and I can bite through any obstacle!"],
    appearance:
      "Messy brown hair, wears a grey hoodie and has distinctive red fang markings on his cheeks.",
    transformations: ["Man Beast Combination Transformation"],
    goals: ["Become the top tracker of Konohagakure", "Protect his comrades"],
    voice_actor: { japanese: "Kosuke Toriumi", english: "Kyle Hebert" },
    first_appearance: "Manga Chapter 34",
    theme_song: "Wild Partner",
  },
];
